package goio

import (
	"github.com/ledzep2/go-i18n/src/pkg/msg"
	"io"
	"text/template"
)

const gotmpl = ` // This file was generated by goi18n. Please do not edit.
package {{.Pkg}}

import (
	"github.com/ledzep2/go-i18n/src/pkg/i18n"
)

{{$locale := .Locale}}
func init() {
	{{range .Messages}}
	i18n.AddTranslation("{{$locale}}", "{{.Context}}", "{{.Content}}", "{{.Translation}}"){{end}}
}
`

var tmpl = template.Must(template.New("gotmpl").Parse(gotmpl))

type data struct {
	Pkg      string
	Locale   string
	Messages []msg.Message
}

type Writer struct {
	d data
}

func NewWriter(pkg, locale string) msg.Writer {
	return &Writer{d: data{Pkg: pkg, Locale: locale}}
}

func (w *Writer) WriteMessages(wr io.Writer, msgs []msg.Message) error {
	w.d.Messages = msgs
	return tmpl.Execute(wr, w.d)
}
